Added some controller mapping ideas.
Team7769/2022-Season pull request #28
Opened 2022-02-17 00:18 UTC by AdamDaMiner

We added some potential controller mappings, but we are not sure as to what buttons we can/can't use. We did speak to some mentors about some potential ideas, and added them to the file. Please, ask questions, and please help if possible. Thank you!

Closes #27.

2022-02-17 14:48 UTC, codingwithcn requested changes
Just fix, the commented brackets, then added a trailing line and you should be good

2022-02-17 14:48 UTC, codingwithcn commented on 2022 Season/src/main/java/frc/robot/Robot.java
> +    if (_operatorController.getRightBumperPressed()) { // Eject}
Same issue here, you are commenting out the last bracket

2022-02-19 19:06 UTC, Koltara approved these changes

2022-02-19 19:09 UTC, codingwithcn approved these changes
It looks all good💪

2022-02-19 19:10 UTC, merged